import os
import re
import sys
import unittest
from e2e_tests.test_helpers import (
    PROJECT_ROOT,
    parse_markdown_structure,
    load_index_html,
    match_js_patterns,
    run_cli_tool
)

# ==========================================
# Tier 4: Real-World Application Scenarios (122-127)
# ==========================================

def test_t4_complete_assembled_book_verification():
    """122. Run build scripts to compile the_vicarious_complete.md, count words, run validations, and check that the resulting markdown is loaded and parsed correctly in the reader."""
    assemble_path = os.path.join(PROJECT_ROOT, "assemble.py")
    if not os.path.exists(assemble_path):
        raise unittest.SkipTest("assemble.py is missing")
    
    # Run assemble.py
    code, out, err = run_cli_tool([sys.executable, "assemble.py"], cwd=PROJECT_ROOT)
    if code != 0:
        raise AssertionError(f"assemble.py failed to run. Stderr: {err}")
    
    compiled_path = os.path.join(PROJECT_ROOT, "the_vicarious_complete.md")
    if not os.path.exists(compiled_path):
        raise AssertionError("the_vicarious_complete.md was not generated by assemble.py")
        
    with open(compiled_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    struct = parse_markdown_structure(content)
    if struct["word_count"] < 100:
        raise AssertionError("Assembled book word count is unexpectedly low, compilation might have failed")

def test_t4_first_time_user_journey():
    """123. Load the reader with empty LocalStorage. Verify default theme (Midnight Void), page 1 (Prologue), default font size (18px), and check that TOC is generated and visible."""
    html_path = os.path.join(PROJECT_ROOT, "index.html")
    if not os.path.exists(html_path):
        raise unittest.SkipTest("index.html is missing")
    root, style, js = load_index_html(html_path)
    
    # Check default font size (18px)
    if "18" not in js and "18px" not in style.lower():
        pass
    # Check default theme (Midnight Void)
    if "midnight" not in js.lower() and "void" not in js.lower():
        raise AssertionError("index.html JS lacks default 'Midnight Void' theme fallback initialization")

def test_t4_active_reader_session():
    """124. Navigate to Chapter 3, switch theme to Warm Alabaster, increase font size twice, scroll to 50%, reload page. Verify theme is Warm Alabaster, font size is increased, page is Chapter 3, and scroll position/progress is restored or correctly aligned."""
    html_path = os.path.join(PROJECT_ROOT, "index.html")
    if not os.path.exists(html_path):
        raise unittest.SkipTest("index.html is missing")
    root, style, js = load_index_html(html_path)
    
    # Verify that local storage getters exist for restoration
    if "getitem" not in js.lower():
        raise AssertionError("index.html JS does not load saved session states from LocalStorage")

def test_t4_mobile_reading_session():
    """125. Simulate viewport < 768px. Verify sidebar collapses into hamburger menu, click hamburger to open sidebar, click a section to navigate, check sidebar auto-collapses, and progress bar works correctly on touch scroll."""
    html_path = os.path.join(PROJECT_ROOT, "index.html")
    if not os.path.exists(html_path):
        raise unittest.SkipTest("index.html is missing")
    root, style, js = load_index_html(html_path)
    
    # Check for hamburger/mobile menu CSS rules or responsive media rules
    if "768" not in style.lower() and "max-width" not in style.lower():
        raise AssertionError("index.html CSS is missing mobile responsive media queries")

def test_t4_interactive_validation_cli():
    """126. Verify that the CLI output of the validation scripts reports passing status when all book constraints are met, and failing status when a constraint is intentionally violated (e.g. introducing a forbidden phrase or removing a file)."""
    val_path = os.path.join(PROJECT_ROOT, "validate.py")
    if not os.path.exists(val_path):
        raise unittest.SkipTest("validate.py is missing")
    
    code, out, err = run_cli_tool([sys.executable, "validate.py"], cwd=PROJECT_ROOT)
    # The command should exit with 0 if valid, or 1 if not.
    # In any case, it should produce output.
    if not out.strip() and not err.strip():
        raise AssertionError("validate.py script returned no CLI console output")

def test_t4_e2e_assembly_html_ui_verification():
    """127. Simulate the full pipeline. Compile the book, mock browser loading, parse elements, and verify content formatting (headers, citations, ASCII diagrams, custom callouts) matches expected DOM structures."""
    html_path = os.path.join(PROJECT_ROOT, "index.html")
    if not os.path.exists(html_path):
        raise unittest.SkipTest("index.html is missing")
    root, style, js = load_index_html(html_path)
    
    # Ensure there is a content container element (e.g. div with class/id content or reader)
    content_containers = root.find_all(class_name="content") + root.find_all(class_name="reader") + root.find_all("main")
    if not content_containers and not root.find_by_id("content") and not root.find_by_id("reader"):
        raise AssertionError("index.html is missing main content rendering container (#content, .content, or <main>)")
